### ISSUE TITLE
PCIE card that supports nokia G-010S-A

### ISSUE THREAD

**Issue by vasilevich** [hwti/G-010S-A#14]
Hello!
Thank you so much for providing help and firmware for this device.
I also have the NOKIA  G-010S-A from my ISP.
it has been tested with the D-LINK DMC-G01LC media converter, and it works fine.
I would like to ask you,
is there any PCIE and/or PCI card which would also support this SFP also on 1GBIT speed
without any issue preferably on any linux distro?

if you know please let me know any models which might support it.
I am very new to the use of SFPS and so far haven't had much experience with their use so I really would like to know.

Thank you for taking the time to read my question.

**Comment by hwti** [comment]
Hello,

At 2.5Gbps, only the BCM57810S cards are known to work.

At 1Gbps, any card should work (unless they are locked to specific SFP modules), but they could require a modification, either on the card, or the SFP, see https://rsaxvc.net/blog/2020/8/15/Nokia_G-010S-A_Pin_6_Issue.html.
I know than Mellanox ConnectX-2 card works at 1Gbps, and does not require any modification.
From https://www.dslreports.com/forum/r31118482-Yes-you-CAN-bypass-the-HomeHub-3000~start=3810, Intel X520 cards should work too.

Note that I only mentioned SFP+ cards : it's usually easy to buy used server cards, they are cheap (if your PC has a x8 PCIe slot, and you don't mind the power consumption).
There are SFP cards too, either very old or low-end, but they are less likely to have been tested.

**Comment by vasilevich** [comment]
@hwti again thank you so much for taking the time to respond to my questions!

basically I plan to build a simple linux "server"  with a desktop motherboard that has 
1 PCI
1 PCIE 2 x1
1 PCIE 2 X16
and use it as the "house router" and "server" at the same time.
I wanted to use the PCIE X16 with the right card,  instead of a separate device media converter
to save space in the box.

1. Do the BCM57810S  or Intel X520 card require any modifications in your opinion? 
such as the 6 pin issue mentioned in the readme of this github.
as you said,  BCM57810S  supports 2.5G I would be happy to spend the extra dollar and prepare for a future potential transition to 2.5.
you think that one does not require physical modifications?
I am currently eyeing cards such as these:
https://www.aliexpress.com/item/1005002383326569.html?_randl_currency=ILS&_randl_shipto=IL&src=google&src=google&albch=shopping&acnt=708-803-3821&slnk=&plac=&mtctp=&albbt=Google_7_shopping&albagn=888888&isSmbAutoCall=false&needSmbHouyi=false&albcp=9441086592&albag=98503410449&trgt=296904914040&crea=he1005002383326569&netw=u&device=c&albpg=296904914040&albpd=he1005002383326569&gclid=Cj0KCQiAieWOBhCYARIsANcOw0xsAeE35yXNEv4MdSCi6npmLMzpvv7iK8RccbCt4fNy18GcxDU_ShMaAsXMEALw_wcB&gclsrc=aw.ds&aff_fcid=3c037aafe4aa47639a4b0ddb8b34006d-1641640286791-01714-UneMJZVf&aff_fsk=UneMJZVf&aff_platform=aaf&sk=UneMJZVf&aff_trace_key=3c037aafe4aa47639a4b0ddb8b34006d-1641640286791-01714-UneMJZVf&terminal_id=a3cb172effdf4afc8ea67e38f8a57797

https://www.aliexpress.com/item/1005002312496661.html?spm=a2g0o.productlist.0.0.184a3088kry06E&algo_pvid=16a1c14e-084a-4502-996d-3664cac9c60a&algo_exp_id=16a1c14e-084a-4502-996d-3664cac9c60a-0&pdp_ext_f=%7B%22sku_id%22%3A%2212000020030905895%22%7D&pdp_pi=-1%3B120.74%3B-1%3B-1%40salePrice%3BILS%3Bsearch-mainSearch

not sure if I will buy exactly from there, but thats about what I found.



2. I also noticed that all the 3 chipsets you mentioned reside in 10G cards,  
will the 1GB nokia sfp gbic work on that? I think its not SFP+, its just SFP as far as I know.
I read that the gbics don't have the ability to negotiate down/up or thats not relevant for the port of the card, rather just the the fibre line between the gibics?


Again, thank you for taking your time to read and answer my questions, I truely appreciate it.

**Comment by hwti** [comment]
SFP+ cards accept SFP modules too, this is backwards compatible.
In the PCIE 2.0 X16 port, you can use one of these cards, and since they have two ports you will be able to use the second one for the LAN (depending on your switch, either with a passive SFP+ DAC for 10Gbps, or an Ethernet SFP(+) for 1/2.5/5/10 Gbps).

BCM57810S cards require the hardware modification to power the G-010S-A, and for 2.5Gbps changing the card configuration in eDiag and the patched kernel module.
See https://www.dslreports.com/forum/r32230041-Internet-Bypassing-the-HH3K-up-to-2-5Gbps-using-a-BCM57810S-NIC, which also has a list of the cards models you can search for.

It looks like the BCM57810S cards are now much more expensive.
I got a used HP 530SFP+ from eBay (Germany) for less than 30€ in 2020.
There is still ones for about 45$-50$, but shipping to Israel (as suggested by your first link) seems expensive.

**Comment by moriel5** [comment]
Hmm... Going by all this, I do wonder how well will Intel cards work at 2.5Gbt/s with the CIG-97S?

**Comment by hwti** [comment]
> Hmm... Going by all this, I do wonder how well will Intel cards work at 2.5Gbt/s with the CIG-97S?

I didn't see any Intel card with HSGMII support.
https://www.cigtech.com/wp-content/uploads/2018/09/G-97S_DataSheet_V2.pdf only mentions `SFP based 1000 Base-X GbE interface`, do you have any information about it using a Intel/Lantiq chipset, or having a 2,5Gbps mode ?

**Comment by moriel5** [comment]
No, I have no information, beyond it being on Bezeq's list of tested SFP ONTs that have no issues on their network.

**Comment by hwti** [comment]
> Unfortunately, I have no information, beyond it being on Bezeq's list of tested SFP ONTs that have no issues on their network.
> 
> The guy at issue #7 was not using Aquantia and Intel SFP+ PCIe cards, I presume?

He uses a media converter, which seems to support HSGMII when the Ethernet side is at 2.5Gbps. Most will only support 1Gbps and 10Gbps on the SFP side, like most of the SFP+ cards.
He tries to use it with the Ethernet side connected to either a router, or a PC with an Aquantia or Intel Ethernet controller (so RJ45, not SFP).

**Comment by moriel5** [comment]
Ah, that certainly makes sense.

**Comment by mlsok** [comment]
> [@hwti](https://github.com/hwti) again thank you so much for taking the time to respond to my questions!
> 
> basically I plan to build a simple linux "server" with a desktop motherboard that has 1 PCI 1 PCIE 2 x1 1 PCIE 2 X16 and use it as the "house router" and "server" at the same time. I wanted to use the PCIE X16 with the right card, instead of a separate device media converter to save space in the shelf / electricity cabling.
> 
> 1. Do the BCM57810S  or Intel X520 card require any modifications in your opinion?
>    such as the 6 pin issue mentioned in the readme of this github.
>    as you said,  BCM57810S  supports 2.5G I would be happy to spend the extra dollar and prepare for a future potential transition to 2.5.
>    you think that one does not require physical modifications?
>    I am currently eyeing cards such as these:
>    BCM57810S :
>    https://www.aliexpress.com/item/1005002383326569.html?_randl_currency=ILS&_randl_shipto=IL&src=google&src=google&albch=shopping&acnt=708-803-3821&slnk=&plac=&mtctp=&albbt=Google_7_shopping&albagn=888888&isSmbAutoCall=false&needSmbHouyi=false&albcp=9441086592&albag=98503410449&trgt=296904914040&crea=he1005002383326569&netw=u&device=c&albpg=296904914040&albpd=he1005002383326569&gclid=Cj0KCQiAieWOBhCYARIsANcOw0xsAeE35yXNEv4MdSCi6npmLMzpvv7iK8RccbCt4fNy18GcxDU_ShMaAsXMEALw_wcB&gclsrc=aw.ds&aff_fcid=3c037aafe4aa47639a4b0ddb8b34006d-1641640286791-01714-UneMJZVf&aff_fsk=UneMJZVf&aff_platform=aaf&sk=UneMJZVf&aff_trace_key=3c037aafe4aa47639a4b0ddb8b34006d-1641640286791-01714-UneMJZVf&terminal_id=a3cb172effdf4afc8ea67e38f8a57797
>    or
>    Intel X520:
>    https://www.aliexpress.com/item/1005002312496661.html?spm=a2g0o.productlist.0.0.184a3088kry06E&algo_pvid=16a1c14e-084a-4502-996d-3664cac9c60a&algo_exp_id=16a1c14e-084a-4502-996d-3664cac9c60a-0&pdp_ext_f=%7B%22sku_id%22%3A%2212000020030905895%22%7D&pdp_pi=-1%3B120.74%3B-1%3B-1%40salePrice%3BILS%3Bsearch-mainSearch
> 
> not sure if I will buy exactly from there, but thats about what I found.
> 
> 2. I also noticed that all the 3 chipsets you mentioned reside in 10G cards,
>    will the 1GB nokia sfp gbic work on that? I think its not SFP+, its just SFP as far as I know.
>    I read that the gbics don't have the ability to negotiate down/up or thats not relevant for the port of the card, rather just the the fibre line between the gibics?
> 
> thank you for taking your time to read and answer my questions, I truely appreciate it.

@vasilevich have you succeeded with pairing your G-010S-A and a PCIe SFP NIC? I tried BCM57810S and other SFP/SFP+ PCIe NICs with no success.
