### ISSUE TITLE
How to update the firmware for Nokia G-010S-A?

### ISSUE THREAD

**Issue by vuducdong** [hwti/G-010S-A#3]
Dear Sir,

How to update the firmware? I use Router Mikrotik or Media converter (with SFP port). Please explain more clearly, if I want to update the firmware, for example: 3FE47111BFHB32.bin. Thank you!

**Comment by yaltar** [comment]
Hi, it's mentioned https://github.com/hwti/G-010S-A#upgrade

You need to first scp the .bin file.

**Comment by Immick** [comment]
> Hi, it's mentioned https://github.com/hwti/G-010S-A#upgrade
> 
> You need to first scp the .bin file.
> 
> 
> 

Sorry, what did you mean by "scp"?

**Comment by hwti** [comment]
> Sorry, what did you mean by "scp"?

This is a way to transfer files over SSH :
 - There is an `scp` command most Unix OS (including Linux), and now on Windows 10
 - For older versions of Windows, there is `pscp.exe` from PuTTY https://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html

> And is there a way to determine what current firmware version is used?

You can connect using SSH (`ssh ONTUSER@192.168.1.10`, password `SUGAR2A041`), and run `upgradestatus`, or `cat /usr/etc/buildinfo`.

**Comment by vuducdong** [comment]
> > Sorry, what did you mean by "scp"?
> 
> This is a way to transfer files over SSH :
> 
> * There is an `scp` command most Unix OS (including Linux), and now on Windows 10
> * For older versions of Windows, there is `pscp.exe` from PuTTY https://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html
> 
> > And is there a way to determine what current firmware version is used?
> 
> You can connect using SSH (`ssh ONTUSER@192.168.1.10`, password `SUGAR2A041`), and run `upgradestatus`, or `cat /usr/etc/buildinfo`.

dear hwti,

I tried update firmware, using pscp, but can't update.

I copied file 3FE47111BFHB32.bin to C hardisk and SSH to 192.168.1.10

========
ONTUSER@SFP:~# upgradestatus
***** get current running image *****
current running image is  image0 !
***** get upgrade status ***********
image0_is_valid=1
image1_is_valid=1
next_active=0
commit=0
boot_fail=0
image0_version=3FE47111BFHB32
image1_version=3FE46398AFGB89

=======
ONTUSER@SFP:~# mtd write C:/3FE47111BFHB32.BIN image1
Couldn't open image file: C:/3FE47111BFHB32.BIN!

**Comment by hwti** [comment]
The "C hardisk" is on your PC, you need to first copy the firmware to the ONT (in `/tmp`, which is stored in RAM) :
```
pscp.exe C:\3FE47111BFHB32.bin ONTUSER@192.168.1.10:/tmp
```

Then you connect to the ONT (`ssh ONTUSER@192.168.1.10`), and :
```
mtd write /tmp/3FE47111BFHB32.BIN image1
update_env_flag 1
reboot
```

For the SLID/PLOAM password, I made a mistake. The gpon.ploam.nPassword value would have been set, but would never change the effective password (which can be checked with `onu gtccg`).
The value needs to be set using the web interface.

**Comment by vuducdong** [comment]
> The "C hardisk" is on your PC, you need to first copy the firmware to the ONT (in `/tmp`, which is stored in RAM) :
> 
> ```
> pscp.exe C:\3FE47111BFHB32.bin ONTUSER@192.168.1.10:/tmp
> ```
> 
> Then you connect to the ONT (`ssh ONTUSER@192.168.1.10`), and :
> 
> ```
> mtd write /tmp/3FE47111BFHB32.BIN image1
> update_env_flag 1
> reboot
> ```
> 
> For the SLID/PLOAM password, I made a mistake. The gpon.ploam.nPassword value would have been set, but would never change the effective password (which can be checked with `onu gtccg`).
> The value needs to be set using the web interface.

Dear, hwti

- with OLT ALU (Alcatel Lucent / Nokia)
I think SLID value on web interface is ok

- with OLT Huawei
if OLT authentication with SN only, G-010S-A only need change by ritool

example:
ritool set MfrID ABCD
ritool set G984Serial 012345678

but if OLT Huawei authentication with SLID (change SLID web interface can't use)

I tried change SLID by ritool with:
ritool set SLID

or:  uci set gpon.ploam.nPassword=
but can't save because can't use command: uci commit
and error is:   " uci: Entry not found "

onu gtccg -- show: differrent SLID 

whether in 5 imageversions, which version will use the command: uci commit ?

Thanks!

**Comment by hwti** [comment]
The value set with `uci set gpon.ploam.nPassword` is saved, but it doesn't matter since it isn't really used on the G-010S-A (at least for the firmwares here).

The authentication depends on your ISP, and sometimes on the OLT type, your original ONT, and when you subscribed.
If you need to set the S/N, use the ritool commands.
If you need to set the SLID, use the web interface.
After a reboot, you should see the values in `onu gtcsng`/`onu gtccg` output.

Perhaps it would be easier if you describe your issue : ISP, what you configured, `onu ploamsg`/`onu gtcsng`/`onu gtccg`  output, ...

I have no specific firmware version to recommend, no one ever reported something working on one version and broken on another.
I don't think they have any differences for authentication, so it's better to try to understand the issue first.

**Comment by vuducdong** [comment]
> The value set with `uci set gpon.ploam.nPassword` is saved, but it doesn't matter since it isn't really used on the G-010S-A (at least for the firmwares here).
> 
> The authentication depends on your ISP, and sometimes on the OLT type, your original ONT, and when you subscribed.
> If you need to set the S/N, use the ritool commands.
> If you need to set the SLID, use the web interface.
> After a reboot, you should see the values in `onu gtcsng`/`onu gtccg` output.
> 
> Perhaps it would be easier if you describe your issue : ISP, what you configured, `onu ploamsg`/`onu gtcsng`/`onu gtccg` output, ...
> 
> I have no specific firmware version to recommend, no one ever reported something working on one version and broken on another.
> I don't think they have any differences for authentication, so it's better to try to understand the issue first.
