### ISSUE TITLE
cant change sn

### ISSUE THREAD

**Issue by aescolastico** [hwti/G-010S-A#31]
Im getting the following error when attempting to use ritool to set a serial

```
ONTUSER@SFP:~# ritool set MfrID ALCLCE
Set scfg descrip=MfrID value=ALCLCE failed. 
```
my firmware is 
```
current running image is  image1 !
***** get upgrade status ***********
image0_is_valid=1
image1_is_valid=1
next_active=1
commit=1
boot_fail=0
image0_version=3FE47111BFHB32
image1_version=3FE46398BFIB36
```
Do i need to flash a new firmware version in order to change sn? If so, can send the image to the device via ssh?

**Comment by wteiken** [comment]
The MfrID is 4 letters (so "ALCL").  The "CE" is likely the start of the serial number.
